### ISSUE TITLE
Tensor 8.6.1 compatibility

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-animesr#4]
After updating vs-dpir I get thousands of 
FakeTensorMode.__torch_dispatch__: aten.detach.default
FakeTensorMode.__torch_dispatch__: aten.detach.default
FakeTensorMode.__torch_dispatch__: aten.mul.Tensor
FakeTensorMode.__torch_dispatch__: aten.mul.Tensor
FakeTensorMode.__torch_dispatch__: aten.detach.default
FakeTensorMode.__torch_dispatch__: aten.detach.default
messages when using vs-animesr

**Comment by HolyWu** [comment]
Always provide a minimum reproducible script or at least the exact arguments you specified for the problematic function. Developers have no crystal ball!

Anyway, I just tried `animesr(trt=True)` and the trt engine can be successfully built on `torch 2.0.1+cu118` + `tensorrt 8.6.1`.

**Comment by Selur** [comment]
I agree, it works with torch 2.0.1+cu118 + tensorrt 8.6.1.
Sorry, about the script, would have provided one if you had created earlier.
