### ISSUE TITLE
Upgrade to Tensor RT 10.0.1

### ISSUE THREAD

**Issue by dan64** [HolyWu/vs-animesr#5]
Hello HolyWu,

   I thank you for all the filters you are developing and I hope that you will find time to upgrade "vs-animesr" to Tensor RT 10.0.1.
   Despite the numerous models added in "vs-realesrgan" I think that "vs-animesr" is still the best.

Thank you,
Dan

**Comment by dan64** [comment]
I tried to modify the file **\_\_init\_\_.py** to support **Tensor RT 10.x**
I was able to successfully get it worlking using fp32, but when I try to use fp16.
I get the following error:


 
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
File "code/__torch__/vsanimesr/vsr_arch.py", line 11, in forward
_0 = torch.pixel_unshuffle(input_2, 4)
__torch___vsanimesr_vsr_arch_MSRSWVSR_trt_engine_000001690DA4C420 = input_0.__torch___vsanimesr_vsr_arch_MSRSWVSR_trt_engine_000001690DA4C420
_1 = ops.tensorrt.execute_engine([input_1, _0, input_3], __torch___vsanimesr_vsr_arch_MSRSWVSR_trt_engine_000001690DA4C420)
 _2, _3, = _1
return (_2, _3)

Traceback of TorchScript, original code (most recent call last):
RuntimeError: [Error thrown at core/runtime/execute_engine.cpp:141] Expected inputs[i].dtype() == expected_type to be true but got false
Expected input tensors to have type Half, found type float
```




To me the correct seems correct, the conversion to fp16 should be managed correctly.
I can't understand where is the error could you help me ?

Dan

P.S.
I attached the modified code.
[__init__.zip](https://github.com/user-attachments/files/16113110/__init__.zip)

**Comment by dan64** [comment]
Problem solved, inside the inference I had to add the following code to ensure fp16 tensor:


        if fp16 and sr.dtype != dtype:
            sr = sr.half()

        if fp16 and state.dtype != dtype:
            state = state.half()


Dan

**Comment by dan64** [comment]
I completed the porting to Tensor RT 10.x
I attached the modified code in the case you are interested to include it in a new release.

Dan
[__init__.zip](https://github.com/user-attachments/files/16115416/__init__.zip)

**Comment by dan64** [comment]
I attached the full package.

Dan
[vsanimesr-1.1.0.tar.gz](https://github.com/user-attachments/files/16116158/vsanimesr-1.1.0.tar.gz)


P.S.
Increase in speed with Tensor RT fp16 and 3 streams: +65%

**Comment by HolyWu** [comment]
This model architecture is not good to use multiple streams because the inference result of the current frame will be used as input to the next frame.
